version: 2
updates:

  - package-ecosystem: cargo
    directory: /server
    schedule:
      interval: weekly
      timezone: US/Central
      day: friday
      time: 18:00

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
      timezone: US/Central
      day: friday
      time: 18:00

  - package-ecosystem: cargo
    directory: /client/native
    schedule:
      interval: weekly
      timezone: US/Central
      day: friday
      time: 18:00
