# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "./client/native",
    "./server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false
